"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
const reais=(v)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);
export default function AtendimentoForm({servicos,produtos,unidades=[],admin=false}){
 const router=useRouter(); const [nome,setNome]=useState(""); const [telefone,setTelefone]=useState(""); const [unidade,setUnidade]=useState(""); const [ss,setSs]=useState([]); const [ps,setPs]=useState([]); const [pag,setPag]=useState("Dinheiro"); const [arquivo,setArquivo]=useState(null); const [erro,setErro]=useState(""); const [salvando,setSalvando]=useState(false);
 const subS=useMemo(()=>ss.reduce((n,id)=>n+Number(servicos.find(x=>x.id===id)?.preco||0),0),[ss,servicos]); const subP=useMemo(()=>ps.reduce((n,x)=>n+Number(produtos.find(p=>p.id===x.id)?.preco||0)*x.quantidade,0),[ps,produtos]);
 const addS=(id)=>{if(id&&!ss.includes(id))setSs([...ss,id])}; const addP=(id)=>{if(!id)return; const a=ps.find(x=>x.id===id); if(a){const prod=produtos.find(x=>x.id===id);if(a.quantidade<prod.estoque)setPs(ps.map(x=>x.id===id?{...x,quantidade:x.quantidade+1}:x))}else setPs([...ps,{id,quantidade:1}])};
 const qtd=(id,d)=>setPs(ps.map(x=>x.id===id?{...x,quantidade:Math.max(1,Math.min(produtos.find(p=>p.id===id).estoque,x.quantidade+d))}:x));
 async function enviar(e){e.preventDefault();if(!nome.trim()||(!ss.length&&!ps.length))return setErro("Informe o cliente e adicione pelo menos um item.");if(admin&&!unidade)return setErro("Selecione a unidade da operação.");setSalvando(true);setErro("");const f=new FormData();f.set("nome",nome);f.set("telefone",telefone);f.set("unidade_id",unidade);f.set("forma_pagamento",pag);f.set("servicos",JSON.stringify(ss.map(id=>({id}))));f.set("produtos",JSON.stringify(ps));if(arquivo)f.set("comprovante",arquivo);const r=await fetch("/api/atendimentos",{method:"POST",body:f});const d=await r.json().catch(()=>({}));setSalvando(false);if(!r.ok)return setErro(d.erro||"Não foi possível finalizar.");router.push(admin?"/painel":"/colaborador");router.refresh()}
 return <form onSubmit={enviar} className="mt-7 grid gap-5 xl:grid-cols-[1fr_380px]">
  {admin&&<label className="rounded-2xl border border-linha bg-papel p-5 xl:col-span-2">Unidade da operação *<select required className="mt-2 w-full rounded-xl border p-3" value={unidade} onChange={e=>setUnidade(e.target.value)}><option value="">Selecione</option>{unidades.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label>}
  <div className="space-y-5"><section className="rounded-2xl border border-linha bg-papel p-5"><h2 className="font-bold">CLIENTE</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm">Nome do cliente *<input className="mt-2 w-full rounded-xl border p-3" required value={nome} onChange={e=>setNome(e.target.value)}/></label><label className="text-sm">Telefone / WhatsApp (opcional)<input className="mt-2 w-full rounded-xl border p-3" value={telefone} onChange={e=>setTelefone(e.target.value)}/></label></div></section>
  <section className="rounded-2xl border border-linha bg-papel p-5"><h2 className="font-bold">SERVIÇOS</h2><select aria-label="Adicionar serviço" className="mt-4 w-full rounded-xl border p-3" value="" onChange={e=>addS(e.target.value)}><option value="">+ ADICIONAR SERVIÇO</option>{servicos.map(x=><option key={x.id} value={x.id}>{x.nome} — {reais(x.preco)}</option>)}</select><div className="mt-3 space-y-2">{ss.map(id=>{const x=servicos.find(s=>s.id===id);return <div key={id} className="flex items-center justify-between rounded-xl bg-black/10 p-3"><span>{x.nome} · {reais(x.preco)}</span><button type="button" onClick={()=>setSs(ss.filter(i=>i!==id))} className="text-[#e2924a]">Remover</button></div>})}</div></section>
  <section className="rounded-2xl border border-linha bg-papel p-5"><h2 className="font-bold">PRODUTOS</h2><select aria-label="Adicionar produto" className="mt-4 w-full rounded-xl border p-3" value="" onChange={e=>addP(e.target.value)}><option value="">+ ADICIONAR PRODUTO</option>{produtos.filter(x=>x.estoque>0).map(x=><option key={x.id} value={x.id}>{x.nome} — {reais(x.preco)} ({x.estoque} em estoque)</option>)}</select><div className="mt-3 space-y-2">{ps.map(i=>{const x=produtos.find(p=>p.id===i.id);return <div key={i.id} className="rounded-xl bg-black/10 p-3"><div className="flex justify-between"><span>{x.nome} · {reais(Number(x.preco)*i.quantidade)}</span><button type="button" onClick={()=>setPs(ps.filter(p=>p.id!==i.id))} className="text-[#e2924a]">Remover</button></div><div className="mt-2 flex items-center gap-3"><button type="button" className="rounded-lg border px-3 py-1" onClick={()=>qtd(i.id,-1)}>-</button><b>{i.quantidade}</b><button type="button" className="rounded-lg border px-3 py-1" disabled={i.quantidade>=x.estoque} onClick={()=>qtd(i.id,1)}>+</button></div></div>})}</div></section></div>
  <aside className="h-fit rounded-2xl border border-[#d27b3c]/50 bg-[#173229] p-5 xl:sticky xl:top-8"><h2 className="text-xl font-bold">COMANDA</h2><p className="mt-5 flex justify-between"><span>Subtotal serviços</span><b>{reais(subS)}</b></p><p className="mt-2 flex justify-between"><span>Subtotal produtos</span><b>{reais(subP)}</b></p><p className="mt-5 flex justify-between border-t border-white/20 pt-5 text-xl"><span>TOTAL</span><b>{reais(subS+subP)}</b></p><label className="mt-6 block text-sm">Forma de pagamento<select className="mt-2 w-full rounded-xl border p-3" value={pag} onChange={e=>setPag(e.target.value)}>{["Dinheiro","Pix","Débito","Crédito"].map(x=><option key={x}>{x}</option>)}</select></label>{pag!=="Dinheiro"&&<label className="mt-5 block text-sm">Anexar comprovante (opcional)<input accept="image/*" capture="environment" type="file" className="mt-2 w-full" onChange={e=>setArquivo(e.target.files?.[0]||null)}/>{arquivo&&<span className="mt-2 flex justify-between text-xs"><span>{arquivo.name}</span><button type="button" onClick={()=>setArquivo(null)}>Remover</button></span>}</label>}{erro&&<p role="alert" className="mt-4 rounded-xl bg-red-950/50 p-3 text-sm text-red-200">{erro}</p>}<button disabled={salvando} className="mt-6 w-full rounded-xl bg-[#c96f32] p-4 font-black text-[#09100d] disabled:opacity-50">{salvando?"FINALIZANDO...":"FINALIZAR ATENDIMENTO"}</button></aside>
 </form>
}
