"use client";
import { useEffect, useState } from "react";
import { Botao, Aviso, entradaCls } from "@/components/ui";
const DIAS = ["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"];
export default function FormProfissional({ id, catalogo }) {
  const [servicos, setServicos] = useState([]); const [horarios, setHorarios] = useState([]); const [msg,setMsg]=useState(null);
  useEffect(() => { fetch(`/api/admin/profissionais/${id}/config`).then((r) => r.json()).then((d) => { setServicos((d.servicos || []).map((s) => s.servico_id)); setHorarios(d.horarios || []); }); }, [id]);
  async function salvar() { setMsg(null); const r = await fetch(`/api/admin/profissionais/${id}/config`, { method:"PUT", headers:{"Content-Type":"application/json"}, body:JSON.stringify({servicos,horarios}) }); const d=await r.json(); setMsg({tipo:r.ok?"ok":"erro",texto:r.ok?"Configuração salva.":d.erro}); }
  return <div className="mt-8 max-w-3xl space-y-8">{msg?<Aviso tipo={msg.tipo}>{msg.texto}</Aviso>:null}<section className="border border-linha bg-papel p-6"><h2 className="font-display text-2xl">Serviços realizados</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{catalogo.map((s)=><label key={s.id} className="flex gap-2"><input type="checkbox" checked={servicos.includes(s.id)} onChange={(e)=>setServicos((a)=>e.target.checked?[...a,s.id]:a.filter((x)=>x!==s.id))}/>{s.nome}</label>)}</div></section><section className="border border-linha bg-papel p-6"><div className="flex justify-between"><h2 className="font-display text-2xl">Jornada</h2><button onClick={()=>setHorarios((a)=>[...a,{dia_semana:1,hora_inicio:"09:00",hora_fim:"18:00"}])} className="text-sm text-couro">+ faixa</button></div><div className="mt-4 space-y-3">{horarios.map((h,i)=><div key={i} className="grid gap-2 sm:grid-cols-[1fr_1fr_1fr_auto]"><select className={entradaCls} value={h.dia_semana} onChange={(e)=>setHorarios((a)=>a.map((x,j)=>j===i?{...x,dia_semana:Number(e.target.value)}:x))}>{DIAS.map((d,n)=><option key={d} value={n}>{d}</option>)}</select><input className={entradaCls} type="time" value={String(h.hora_inicio).slice(0,5)} onChange={(e)=>setHorarios((a)=>a.map((x,j)=>j===i?{...x,hora_inicio:e.target.value}:x))}/><input className={entradaCls} type="time" value={String(h.hora_fim).slice(0,5)} onChange={(e)=>setHorarios((a)=>a.map((x,j)=>j===i?{...x,hora_fim:e.target.value}:x))}/><button onClick={()=>setHorarios((a)=>a.filter((_,j)=>j!==i))}>Remover</button></div>)}</div></section><Botao onClick={salvar}>Salvar serviços e horários</Botao></div>;
}
