import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { exigirPapel } from "@/lib/auth";
import { resolverUnidadeEfetiva } from "@/lib/unidades";
import { diaLocal, limitesDoDia } from "@/lib/formato";
const SEQ=["ENTRADA","INICIO_INTERVALO","RETORNO","SAIDA"];
const distancia=(a,b,c,d)=>{const r=6371000,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180;const z=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return 2*r*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))};
export async function GET(){const u=await exigirPapel(["colaborador"]);if(!u)return NextResponse.json({erro:"Sem permissão."},{status:403});const hoje=diaLocal(),{de,ate}=limitesDoDia(hoje),unidadeId=await resolverUnidadeEfetiva(u.id,hoje,u.unidade_id);const [unidade,registros]=await Promise.all([unidadeId?db.from("unidades").select("id,nome,latitude,longitude,raio_ponto_m").eq("id",unidadeId).maybeSingle():{data:null,error:null},db.from("ponto_registros").select("id,tipo,status,registrado_em,distancia_m,accuracy").eq("colaborador_id",u.id).gte("registrado_em",de).lte("registrado_em",ate).order("registrado_em")]);if(unidade.error||registros.error)return NextResponse.json({erro:"Não foi possível carregar o ponto."},{status:500});const feitos=registros.data||[],ultima=feitos.at(-1);return NextResponse.json({unidade:unidade.data,registros:feitos,proxima:SEQ[ultima?SEQ.indexOf(ultima.tipo)+1:0]||null})}
export async function POST(req){const u=await exigirPapel(["colaborador"]);if(!u)return NextResponse.json({erro:"Sem permissão."},{status:403});const b=await req.json().catch(()=>({}));const lat=Number(b.latitude),lon=Number(b.longitude),accuracy=Number(b.accuracy);if(!Number.isFinite(lat)||!Number.isFinite(lon)||!Number.isFinite(accuracy))return NextResponse.json({erro:"Localização inválida."},{status:400});const hoje=diaLocal(),{de,ate}=limitesDoDia(hoje),unidadeId=await resolverUnidadeEfetiva(u.id,hoje,u.unidade_id);if(!unidadeId)return NextResponse.json({erro:"Sua unidade de hoje não está definida."},{status:409});const [ur,rr]=await Promise.all([db.from("unidades").select("id,nome,latitude,longitude,raio_ponto_m").eq("id",unidadeId).single(),db.from("ponto_registros").select("tipo").eq("colaborador_id",u.id).gte("registrado_em",de).lte("registrado_em",ate).order("registrado_em",{ascending:false}).limit(1)]);if(ur.error) return NextResponse.json({erro:"Unidade inválida."},{status:409});const esperada=SEQ[rr.data?.[0]?SEQ.indexOf(rr.data[0].tipo)+1:0];if(!esperada||b.tipo!==esperada)return NextResponse.json({erro:"Sequência de ponto inválida."},{status:409});const un=ur.data;if(un.latitude==null||un.longitude==null||un.raio_ponto_m==null)return NextResponse.json({erro:"A unidade ainda não possui coordenadas e raio configurados."},{status:409});const dist=distancia(lat,lon,Number(un.latitude),Number(un.longitude));const status=accuracy>100?"PRECISAO_INSUFICIENTE":dist>Number(un.raio_ponto_m)?"FORA_DA_AREA":"VALIDADO";const {data,error}=await db.from("ponto_registros").insert({colaborador_id:u.id,unidade_id:unidadeId,tipo:b.tipo,latitude:lat,longitude:lon,accuracy,distancia_m:Math.round(dist*100)/100,status}).select("id,tipo,status,registrado_em,distancia_m,accuracy").single();if(error)return NextResponse.json({erro:"Não foi possível registrar o ponto."},{status:400});return NextResponse.json({registro:data})}
